Repository boostcampwm-2022/android01-UCMC, pull requests merged in 2022-12, with the labels that each got.

#109 Feature: #106 채팅 노티피케이션 연결, 채팅 목록 드자인
  data/src/main/java/com/gta/data/source/LicenseDataSource.kt
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/gta/presentation/NotificationService.kt
  presentation/src/main/java/com/gta/presentation/di/StreamModule.kt
  presentation/src/main/java/com/gta/presentation/ui/cardetail/CarDetailViewModel.kt
  presentation/src/main/java/com/gta/presentation/ui/chatting/list/ChattingListFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/chatting/list/ChattingListViewHolder.kt
  presentation/src/main/java/com/gta/presentation/ui/login/LoginActivity.kt
  presentation/src/main/java/com/gta/presentation/ui/mypage/license/MyPageLicenseViewModel.kt
  presentation/src/main/res/layout/item_chatting_list.xml
  presentation/src/main/res/values/strings.xml
Labels: ✨ Feature, ✒ Reviewing, 민성

#111 Feature: #110 예약 관련 DB 쿼리 수정_진짜_최종
  data/src/main/java/com/gta/data/di/RepositoryModule.kt
  data/src/main/java/com/gta/data/model/UserInfo.kt
  data/src/main/java/com/gta/data/repository/CarRepositoryImpl.kt
  data/src/main/java/com/gta/data/repository/LicenseRepositoryImpl.kt
  data/src/main/java/com/gta/data/repository/MyPageRepositoryImpl.kt
  data/src/main/java/com/gta/data/repository/ReservationRepositoryImpl.kt
  data/src/main/java/com/gta/data/repository/ReviewRepositoryImpl.kt
  data/src/main/java/com/gta/data/repository/UserRepositoryImpl.kt
  data/src/main/java/com/gta/data/source/CarDataSource.kt
  data/src/main/java/com/gta/data/source/LoginDataSource.kt
  data/src/main/java/com/gta/data/source/ReservationDataSource.kt
  data/src/main/java/com/gta/data/source/StorageDataSource.kt
  domain/src/main/java/com/gta/domain/model/Reservation.kt
  domain/src/main/java/com/gta/domain/repository/ReservationRepository.kt
  domain/src/main/java/com/gta/domain/repository/ReviewRepository.kt
  domain/src/main/java/com/gta/domain/repository/UserRepository.kt
  domain/src/main/java/com/gta/domain/usecase/cardetail/GetNowRentCarUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/cardetail/GetUseStateAboutCarUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/reservation/CreateReservationUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/review/GetReviewDTOUseCase.kt
  presentation/src/main/java/com/gta/presentation/ui/reservation/ReservationViewModel.kt
  presentation/src/main/java/com/gta/presentation/ui/review/ReviewViewModel.kt
Labels: ✨ Feature, ✒ Reviewing, 민성

#112 Feature: #102 Notification DB 저장
  data/src/main/java/com/gta/data/repository/NotificationRepositoryImpl.kt
  data/src/main/java/com/gta/data/source/NotificationDataSource.kt
  domain/src/main/java/com/gta/domain/model/Notification.kt
  domain/src/main/java/com/gta/domain/repository/NotificationRepository.kt
  domain/src/main/java/com/gta/domain/usecase/SendNotificationUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/reservation/CreateReservationUseCase.kt
Labels: ✨ Feature, ✒ Reviewing, 주영

#115 feature: #113 채팅방에 들어와 있을 때는 채널을 Mute하기
  presentation/src/main/java/com/gta/presentation/ui/cardetail/CarDetailViewModel.kt
  presentation/src/main/java/com/gta/presentation/ui/chatting/chat/ChattingFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/chatting/chat/ChattingViewModel.kt
  presentation/src/main/java/com/gta/presentation/ui/chatting/list/ChattingListViewHolder.kt
Labels: ✨ Feature, ✒ Reviewing, 민성

#116 Feature: #54 반납하기 화면 구현
  data/src/main/java/com/gta/data/repository/ReservationRepositoryImpl.kt
  data/src/main/java/com/gta/data/repository/UserRepositoryImpl.kt
  data/src/main/java/com/gta/data/source/ReservationDataSource.kt
  domain/src/main/java/com/gta/domain/model/Reservation.kt
  domain/src/main/java/com/gta/domain/model/SimpleReservation.kt
  domain/src/main/java/com/gta/domain/repository/ReservationRepository.kt
  domain/src/main/java/com/gta/domain/repository/UserRepository.kt
  domain/src/main/java/com/gta/domain/usecase/cardetail/GetNowRentCarUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/cardetail/GetUseStateAboutCarUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/returncar/ReturnCarUseCase.kt
  presentation/src/main/java/com/gta/presentation/ui/cardetail/CarDetailFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/returncar/ReturnCarFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/returncar/ReturnCarViewModel.kt
  presentation/src/main/java/com/gta/presentation/ui/review/ReviewFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/review/ReviewViewModel.kt
  presentation/src/main/java/com/gta/presentation/util/DateUtil.kt
  presentation/src/main/res/layout/fragment_return_car.xml
  presentation/src/main/res/navigation/nav_main.xml
  presentation/src/main/res/values/strings.xml
Labels: ✨ Feature, ✒ Reviewing, 주영

#114 Feature: #63 Firebase Daily Crontab Function 작성
  .firebaserc
  firebase.json
  functions/.eslintrc.js
  functions/.gitignore
  functions/index.js
  functions/package-lock.json
  functions/package.json
Labels: ✨ Feature, ✒ Reviewing, 동훈

#117 Feature: #43 예약 수락/거절 화면
  .gitignore
  data/src/main/java/com/gta/data/model/Car.kt
  data/src/main/java/com/gta/data/repository/CarRepositoryImpl.kt
  data/src/main/java/com/gta/data/repository/NotificationRepositoryImpl.kt
  data/src/main/java/com/gta/data/repository/ReviewRepositoryImpl.kt
  data/src/main/java/com/gta/data/repository/UserRepositoryImpl.kt
  data/src/main/java/com/gta/data/source/UserDataSource.kt
  domain/src/main/java/com/gta/domain/model/CarRentInfo.kt
  domain/src/main/java/com/gta/domain/model/Notification.kt
  domain/src/main/java/com/gta/domain/model/Reservation.kt
  domain/src/main/java/com/gta/domain/model/UserReview.kt
  domain/src/main/java/com/gta/domain/usecase/reservation/FinishReservationUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/reservation/GetReservationUseCase.kt
  presentation/src/main/java/com/gta/presentation/NotificationService.kt
  presentation/src/main/java/com/gta/presentation/ui/cardetail/edit/CarEditFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/mypage/license/MyPageLicenseFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/nickname/NicknameFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/notification/NotificationFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/reservation/ReservationFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/reservation/ReservationViewModel.kt
  presentation/src/main/java/com/gta/presentation/ui/reservation/check/ReservationCheckFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/reservation/check/ReservationCheckViewModel.kt
  presentation/src/main/res/layout/fragment_notification.xml
  presentation/src/main/res/layout/fragment_reservation_request.xml
  presentation/src/main/res/navigation/nav_main.xml
  presentation/src/main/res/values/strings.xml
Labels: ✨ Feature, ✒ Reviewing, 동훈

#122 Fix: #121 회원가입 시 이용약관 안보이는 버그
  data/src/main/java/com/gta/data/repository/CarRepositoryImpl.kt
  data/src/main/java/com/gta/data/repository/NotificationRepositoryImpl.kt
  data/src/main/java/com/gta/data/repository/ReviewRepositoryImpl.kt
  data/src/main/java/com/gta/data/repository/UserRepositoryImpl.kt
  data/src/main/java/com/gta/data/source/UserDataSource.kt
Labels: 🐞 Fix, ✒ Reviewing, 동훈

#123 Feature: #119 지도 관련 디테일 및 버그 수정
  data/src/main/java/com/gta/data/model/SearchResult.kt
  presentation/src/main/java/com/gta/presentation/ui/map/MapFragment.kt
Labels: ✨ Feature, ✒ Reviewing, 동훈

#124 Feature: #120 신고 동작, 거래 내역 버튼 분리, EventFlow 적용
  data/src/main/java/com/gta/data/di/RepositoryModule.kt
  data/src/main/java/com/gta/data/repository/ReportRepositoryImpl.kt
  data/src/main/java/com/gta/data/source/UserDataSource.kt
  data/src/main/res/values/string.xml
  domain/src/main/java/com/gta/domain/model/UCMCResult.kt
  domain/src/main/java/com/gta/domain/repository/ReportRepository.kt
  domain/src/main/java/com/gta/domain/usecase/user/ReportUserUseCase.kt
  presentation/src/main/java/com/gta/presentation/ui/base/BaseFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/cardetail/CarDetailFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/cardetail/CarDetailViewModel.kt
  presentation/src/main/java/com/gta/presentation/ui/cardetail/OwnerProfileFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/cardetail/OwnerProfileViewModel.kt
  presentation/src/main/java/com/gta/presentation/util/EventFlow.kt
  presentation/src/main/res/drawable/ic_mypage_deal_inverse.xml
  presentation/src/main/res/layout/fragment_mypage.xml
  presentation/src/main/res/layout/fragment_owner_profile.xml
  presentation/src/main/res/values/strings.xml
Labels: ✨ Feature, ✒ Reviewing, 민성

#126 Feat: #125 스플래시 스크린 로그인 확인
  presentation/src/main/java/com/gta/presentation/ui/login/LoginActivity.kt
  presentation/src/main/java/com/gta/presentation/ui/login/LoginViewModel.kt
  presentation/src/main/res/layout/fragment_map.xml
Labels: ✨ Feature, ✒ Reviewing, 동훈

#129 Fix: #118 예약 화면 수정
  data/src/main/java/com/gta/data/repository/ReservationRepositoryImpl.kt
  data/src/main/java/com/gta/data/source/ReservationDataSource.kt
  domain/src/main/java/com/gta/domain/model/Reservation.kt
  presentation/src/main/java/com/gta/presentation/ui/reservation/ReservationFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/reservation/ReservationViewModel.kt
  presentation/src/main/java/com/gta/presentation/ui/reservation/check/ReservationCheckFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/reservation/check/ReservationCheckViewModel.kt
Labels: 🐞 Fix, ✒ Reviewing, 주영

#133 Feat: #131 Firebase Function 변경
  functions/index.js
Labels: ✨ Feature, ✒ Reviewing, 동훈

#134 Feature : #130 예외 처리 (프로필 사진 변경, 닉네임 변경, 리뷰 기능, 사진 등록)
  data/src/main/java/com/gta/data/di/RepositoryModule.kt
  data/src/main/java/com/gta/data/repository/LicenseRepositoryImpl.kt
  data/src/main/java/com/gta/data/repository/MyPageRepositoryImpl.kt
  data/src/main/java/com/gta/data/repository/NicknameRepositoryImpl.kt
  data/src/main/java/com/gta/data/repository/PinkSlipRepositoryImpl.kt
  data/src/main/java/com/gta/data/repository/ReportRepositoryImpl.kt
  data/src/main/java/com/gta/data/repository/ReviewRepositoryImpl.kt
  data/src/main/java/com/gta/data/source/LicenseDataSource.kt
  data/src/main/java/com/gta/data/source/ReviewDataSource.kt
  data/src/main/res/values/string.xml
  domain/src/main/java/com/gta/domain/model/UCMCException.kt
  domain/src/main/java/com/gta/domain/model/UCMCResult.kt
  domain/src/main/java/com/gta/domain/repository/LicenseRepository.kt
  domain/src/main/java/com/gta/domain/repository/MyPageRepository.kt
  domain/src/main/java/com/gta/domain/repository/NicknameRepository.kt
  domain/src/main/java/com/gta/domain/repository/PinkSlipRepository.kt
  domain/src/main/java/com/gta/domain/repository/ReviewRepository.kt
  domain/src/main/java/com/gta/domain/usecase/license/GetLicenseFromDatabaseUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/license/GetLicenseFromImageUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/license/SetLicenseUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/mypage/DeleteThumbnailUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/mypage/SetThumbnailUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/nickname/UpdateNicknameUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/pinkslip/GetPinkSlipUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/pinkslip/SetPinkSlipUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/review/AddReviewUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/review/GetReviewDTOUseCase.kt
  presentation/src/main/java/com/gta/presentation/ui/cardetail/CarDetailFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/cardetail/OwnerProfileFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/license/guide/LicenseGuideFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/license/registration/LicenseRegistrationFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/license/registration/LicenseRegistrationViewModel.kt
  presentation/src/main/java/com/gta/presentation/ui/mypage/MyPageFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/mypage/MyPageViewModel.kt
  presentation/src/main/java/com/gta/presentation/ui/mypage/license/MyPageLicenseFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/mypage/license/MyPageLicenseViewModel.kt
  presentation/src/main/java/com/gta/presentation/ui/nickname/NicknameFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/nickname/NicknameViewModel.kt
  presentation/src/main/java/com/gta/presentation/ui/pinkslip/guide/PinkSlipGuideFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/pinkslip/registration/PinkSlipRegistrationFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/pinkslip/registration/PinkSlipRegistrationViewModel.kt
  presentation/src/main/java/com/gta/presentation/ui/review/ReviewFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/review/ReviewViewModel.kt
  presentation/src/main/res/navigation/nav_main.xml
  presentation/src/main/res/values/strings.xml
Labels: ✨ Feature, ✒ Reviewing, 민성

#135 Feature: #132 예외 처리 및 EventFlow 적용
  data/src/main/java/com/gta/data/repository/CarRepositoryImpl.kt
  data/src/main/java/com/gta/data/repository/MapRepositoryImpl.kt
  data/src/main/java/com/gta/data/repository/ReservationRepositoryImpl.kt
  data/src/main/java/com/gta/data/source/CarDataSource.kt
  domain/src/main/java/com/gta/domain/model/UCMCException.kt
  domain/src/main/java/com/gta/domain/repository/CarRepository.kt
  domain/src/main/java/com/gta/domain/repository/MapRepository.kt
  domain/src/main/java/com/gta/domain/repository/ReservationRepository.kt
  domain/src/main/java/com/gta/domain/usecase/cardetail/GetCarDetailDataUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/cardetail/GetOwnerCarsUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/cardetail/RemoveCarUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/map/GetNearCarsUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/map/GetSearchAddressUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/reservation/GetReservationUseCase.kt
  presentation/src/main/java/com/gta/presentation/ui/base/BaseFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/cardetail/CarDetailFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/cardetail/CarDetailViewModel.kt
  presentation/src/main/java/com/gta/presentation/ui/cardetail/OwnerProfileFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/cardetail/OwnerProfileViewModel.kt
  presentation/src/main/java/com/gta/presentation/ui/cardetail/edit/CarEditFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/cardetail/edit/CarEditViewModel.kt
  presentation/src/main/java/com/gta/presentation/ui/login/LoginActivity.kt
  presentation/src/main/java/com/gta/presentation/ui/map/MapFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/map/MapViewModel.kt
  presentation/src/main/java/com/gta/presentation/ui/mypage/mycars/MyCarsFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/mypage/mycars/MyCarsViewModel.kt
  presentation/src/main/java/com/gta/presentation/ui/reservation/check/ReservationCheckFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/reservation/check/ReservationCheckViewModel.kt
  presentation/src/main/res/values/strings.xml
Labels: ✨ Feature, ✒ Reviewing, 동훈

#136 Feature:#65 내차 수정하기 (지도)
  data/src/main/java/com/gta/data/model/AddressResult.kt
  data/src/main/java/com/gta/data/model/Car.kt
  data/src/main/java/com/gta/data/repository/MapRepositoryImpl.kt
  data/src/main/java/com/gta/data/service/AddressSearchService.kt
  data/src/main/java/com/gta/data/source/MapDataSource.kt
  domain/src/main/java/com/gta/domain/model/CarDetail.kt
  domain/src/main/java/com/gta/domain/model/Coordinate.kt
  domain/src/main/java/com/gta/domain/repository/MapRepository.kt
  presentation/src/main/java/com/gta/domain/usecase/cardetail/edit/GetCoordinateLocationUseCase.kt
  presentation/src/main/java/com/gta/presentation/ui/MainActivity.kt
  presentation/src/main/java/com/gta/presentation/ui/cardetail/edit/CarEditFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/cardetail/edit/CarEditMapFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/cardetail/edit/CarEditViewModel.kt
  presentation/src/main/java/com/gta/presentation/ui/map/MapFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/map/MapViewModel.kt
  presentation/src/main/res/layout/fragment_car_edit.xml
  presentation/src/main/res/layout/fragment_car_edit_map.xml
  presentation/src/main/res/navigation/nav_main.xml
  presentation/src/main/res/values/strings.xml
Labels: ✨ Feature, ✒ Reviewing, 현지

#139 Feature:#127 거래 내역 화면 구현
  buildSrc/src/main/java/com/gta/buildsrc/Dependencies.kt
  data/src/main/java/com/gta/data/di/RepositoryModule.kt
  data/src/main/java/com/gta/data/repository/MapRepositoryImpl.kt
  data/src/main/java/com/gta/data/repository/TransactionRepositoryImpl.kt
  data/src/main/java/com/gta/data/source/TransactionDataSource.kt
  domain/src/main/java/com/gta/domain/model/CarDetail.kt
  domain/src/main/java/com/gta/domain/model/Reservation.kt
  domain/src/main/java/com/gta/domain/model/SimpleReservation.kt
  domain/src/main/java/com/gta/domain/model/Transaction.kt
  domain/src/main/java/com/gta/domain/repository/TransactionRepository.kt
  domain/src/main/java/com/gta/domain/usecase/transaction/GetTransactionsUseCase.kt
  presentation/src/main/java/com/gta/presentation/model/EmptyModel.kt
  presentation/src/main/java/com/gta/presentation/model/TransactionState.kt
  presentation/src/main/java/com/gta/presentation/model/TransactionUserState.kt
  presentation/src/main/java/com/gta/presentation/ui/BindingAdapter.kt
  presentation/src/main/java/com/gta/presentation/ui/cardetail/CarDetailFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/cardetail/edit/CarEditFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/cardetail/edit/CarEditViewModel.kt
  presentation/src/main/java/com/gta/presentation/ui/map/MapViewModel.kt
  presentation/src/main/java/com/gta/presentation/ui/mypage/MyPageFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/transaction/TransactionFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/transaction/TransactionListAdapter.kt
  presentation/src/main/java/com/gta/presentation/ui/transaction/TransactionListFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/transaction/TransactionListViewModel.kt
  presentation/src/main/java/com/gta/presentation/ui/transaction/TransactionPagerAdapter.kt
  presentation/src/main/res/layout/fragment_transaction.xml
  presentation/src/main/res/layout/fragment_transaction_list.xml
  presentation/src/main/res/layout/item_transaction.xml
  presentation/src/main/res/navigation/nav_main.xml
  presentation/src/main/res/values/strings.xml
Labels: ✨ Feature, ✒ Reviewing, 주영

#148 Test: #142 ReportRepository 테스트 코드 작성
  build.gradle.kts
  buildSrc/src/main/java/com/gta/buildsrc/Dependencies.kt
  data/build.gradle.kts
  data/src/main/java/com/gta/data/repository/ReportRepositoryImpl.kt
  data/src/test/java/com/gta/data/ExampleUnitTest.kt
  data/src/test/java/com/gta/data/ReportUnitTest.kt
  domain/src/main/java/com/gta/domain/repository/ReportRepository.kt
Labels: ✅ Test, ✒ Reviewing, 민성

#155 Feature: #149 로그인 화면 예외 처리
  data/src/main/java/com/gta/data/repository/LoginRepositoryImpl.kt
  domain/src/main/java/com/gta/domain/model/LoginResult.kt
  domain/src/main/java/com/gta/domain/repository/LoginRepository.kt
  domain/src/main/java/com/gta/domain/usecase/login/CheckCurrentUserUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/login/SignUpUseCase.kt
  presentation/src/main/java/com/gta/presentation/ui/MainActivity.kt
  presentation/src/main/java/com/gta/presentation/ui/MainViewModel.kt
  presentation/src/main/java/com/gta/presentation/ui/login/LoginActivity.kt
  presentation/src/main/java/com/gta/presentation/ui/login/LoginViewModel.kt
  presentation/src/main/res/values/strings.xml
Labels: ✨ Feature, ✒ Reviewing, 민성

#156 Fix: 예약 확인 화면 버그 수정
  presentation/src/main/java/com/gta/presentation/ui/reservation/check/ReservationCheckFragment.kt
  presentation/src/main/res/layout/fragment_reservation.xml
Labels: 🐞 Fix, ✒ Reviewing, 동훈

#159 Feature: #157 디자인 수정 (마이페이지, 닉네임, 운전자 등록, 자동차 등록), 단위 테스트 (LoginRepository, LicenseRepository)
  build.gradle.kts
  buildSrc/src/main/java/com/gta/buildsrc/Dependencies.kt
  data/build.gradle.kts
  data/src/main/java/com/gta/data/di/LicenseModule.kt
  data/src/main/java/com/gta/data/repository/LicenseRepositoryImpl.kt
  data/src/main/java/com/gta/data/repository/LoginRepositoryImpl.kt
  data/src/main/java/com/gta/data/source/LicenseDataSource.kt
  data/src/main/java/com/gta/data/util/EmptyUtil.kt
  data/src/test/java/com/gta/data/LicenseRepositoryUnitTest.kt
  data/src/test/java/com/gta/data/LoginRepositoryUnitTest.kt
  data/src/test/java/com/gta/data/ReportRepositoryUnitTest.kt
  data/src/test/java/com/gta/data/TestUtil.kt
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/gta/presentation/ui/license/registration/LicenseRegistrationFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/license/registration/LicenseRegistrationViewModel.kt
  presentation/src/main/java/com/gta/presentation/ui/nickname/NicknameFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/pinkslip/registration/PinkSlipRegistrationFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/pinkslip/registration/PinkSlipRegistrationViewModel.kt
  presentation/src/main/res/drawable/ic_mypage_car.xml
  presentation/src/main/res/drawable/ic_mypage_deal.xml
  presentation/src/main/res/drawable/ic_mypage_deal_inverse.xml
  presentation/src/main/res/drawable/ic_mypage_edit.xml
  presentation/src/main/res/drawable/ic_mypage_fine.xml
  presentation/src/main/res/drawable/ic_mypage_license.xml
  presentation/src/main/res/drawable/ic_mypage_payment.xml
  presentation/src/main/res/drawable/ic_mypage_thumb.xml
  presentation/src/main/res/layout/fragment_camera_guide.xml
  presentation/src/main/res/layout/fragment_license_registration.xml
  presentation/src/main/res/layout/fragment_mypage.xml
  presentation/src/main/res/layout/fragment_nickname.xml
  presentation/src/main/res/layout/fragment_pink_slip_registration.xml
  presentation/src/main/res/values/styles.xml
Labels: ✨ Feature, ✒ Reviewing, 민성

#163 Feature: #160 마커 색상 변경 로직 수정 & 마커 리스트 저장 로직 변경
  presentation/src/main/java/com/gta/presentation/ui/map/MapFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/map/MapViewModel.kt
Labels: ✨ Feature, ✒ Reviewing, 동훈

#162 Fix: #161 예약 수락/거절 시 중복 생성 버그 수정
  domain/src/main/java/com/gta/domain/usecase/reservation/FinishReservationUseCase.kt
  presentation/src/main/java/com/gta/presentation/ui/reservation/check/ReservationCheckViewModel.kt
Labels: 🐞 Fix, ✒ Reviewing, 동훈

#165 Feature: #140 예약 화면, 반납 화면 예외처리 Result로 감싸 전달, View에 표시
  data/src/main/java/com/gta/data/repository/CarRepositoryImpl.kt
  data/src/main/java/com/gta/data/repository/NotificationRepositoryImpl.kt
  data/src/main/java/com/gta/data/repository/ReservationRepositoryImpl.kt
  data/src/main/java/com/gta/data/source/NotificationDataSource.kt
  domain/src/main/java/com/gta/domain/model/Reservation.kt
  domain/src/main/java/com/gta/domain/repository/CarRepository.kt
  domain/src/main/java/com/gta/domain/repository/NotificationRepository.kt
  domain/src/main/java/com/gta/domain/repository/ReservationRepository.kt
  domain/src/main/java/com/gta/domain/usecase/SendNotificationUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/cardetail/GetUseStateAboutCarUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/reservation/CreateReservationUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/reservation/FinishReservationUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/reservation/GetCarRentInfoUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/returncar/ReturnCarUseCase.kt
  presentation/src/main/java/com/gta/presentation/ui/MainActivity.kt
  presentation/src/main/java/com/gta/presentation/ui/reservation/PaymentFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/reservation/ReservationFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/reservation/ReservationViewModel.kt
  presentation/src/main/java/com/gta/presentation/ui/reservation/check/ReservationCheckFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/reservation/check/ReservationCheckViewModel.kt
  presentation/src/main/java/com/gta/presentation/ui/returncar/ReturnCarFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/returncar/ReturnCarViewModel.kt
  presentation/src/main/res/layout/fragment_payment.xml
  presentation/src/main/res/layout/fragment_reservation.xml
  presentation/src/main/res/navigation/nav_main.xml
  presentation/src/main/res/values/strings.xml
Labels: ✨ Feature, ✒ Reviewing, 주영

#171 Feature : #166 단위 테스트 작성 (MyPageRepository, NicknameRepository, PinkSlipRepository, ReviewRepository)
  data/src/main/java/com/gta/data/di/PinkSlipModule.kt
  data/src/main/java/com/gta/data/repository/MyPageRepositoryImpl.kt
  data/src/main/java/com/gta/data/repository/PinkSlipRepositoryImpl.kt
  data/src/main/java/com/gta/data/source/PinkSlipDataSource.kt
  data/src/test/java/com/gta/data/LicenseRepositoryUnitTest.kt
  data/src/test/java/com/gta/data/MyPageRepositoryUnitTest.kt
  data/src/test/java/com/gta/data/NicknameRepositoryUnitTest.kt
  data/src/test/java/com/gta/data/PinkSlipRepositoryUnitTest.kt
  data/src/test/java/com/gta/data/ReportRepositoryUnitTest.kt
  data/src/test/java/com/gta/data/ReviewRepositoryUnitTest.kt
  data/src/test/java/com/gta/data/TestUtil.kt
  domain/src/main/java/com/gta/domain/repository/MyPageRepository.kt
  domain/src/main/java/com/gta/domain/usecase/mypage/SetThumbnailUseCase.kt
  presentation/src/main/java/com/gta/presentation/ui/mypage/MyPageViewModel.kt
Labels: ✅ Test, ✒ Reviewing, 민성

#172 Feature: #167 Map Repository, Reservation Repository 테스트 코드 작성
  app/build.gradle.kts
  data/src/main/java/com/gta/data/repository/MapRepositoryImpl.kt
  data/src/test/java/com/gta/data/MapFragmentUnitTest.kt
  data/src/test/java/com/gta/data/ReservationRepositoryUnitTest.kt
Labels: ✅ Test, ✒ Reviewing, 동훈

#174 Feature: #168 MessageTokenRepository, NotificationRepository 단위 테스트
  data/src/test/java/com/gta/data/MessageTokenRepositoryUnitTest.kt
  data/src/test/java/com/gta/data/NotificationRepositoryUnitTest.kt
Labels: ✅ Test, ✒ Reviewing, 주영

#173 Feature:#92 단위 테스트 작성(UserRepository, 일부 CarRepository)
  data/src/test/java/com/gta/data/CarRepositoryUnitTest.kt
  data/src/test/java/com/gta/data/UserRepositoryUnitTest.kt
Labels: ✅ Test, ✒ Reviewing, 현지

#176 Feature: #175 로그인 기능 리팩토링
  data/src/main/java/com/gta/data/repository/LoginRepositoryImpl.kt
  data/src/main/java/com/gta/data/source/LoginDataSource.kt
  data/src/test/java/com/gta/data/LoginRepositoryUnitTest.kt
  data/src/test/java/com/gta/data/NotificationRepositoryUnitTest.kt
  domain/src/main/java/com/gta/domain/model/UCMCException.kt
  domain/src/main/java/com/gta/domain/repository/LoginRepository.kt
  domain/src/main/java/com/gta/domain/usecase/login/CheckCurrentUserUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/login/SignUpUseCase.kt
  presentation/src/main/java/com/gta/presentation/ui/cardetail/OwnerProfileFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/cardetail/OwnerProfileViewModel.kt
  presentation/src/main/java/com/gta/presentation/ui/login/LoginViewModel.kt
  presentation/src/main/java/com/gta/presentation/ui/map/MapFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/reservation/check/ReservationCheckViewModel.kt
  presentation/src/main/res/layout/include_car_summary.xml
Labels: 🔨 Refactor, ✒ Reviewing, 민성

#179 Feature:#78 자잘한 버그 수정 및 리팩토링
  data/src/main/java/com/gta/data/repository/MapRepositoryImpl.kt
  presentation/src/main/java/com/gta/presentation/ui/BindingAdapter.kt
  presentation/src/main/java/com/gta/presentation/ui/cardetail/CarDetailFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/cardetail/CarDetailViewModel.kt
  presentation/src/main/java/com/gta/presentation/ui/cardetail/OwnerProfileFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/cardetail/OwnerProfileViewModel.kt
  presentation/src/main/java/com/gta/presentation/ui/cardetail/edit/CarEditFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/cardetail/edit/CarEditMapFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/notification/NotificationListFragment.kt
  presentation/src/main/res/layout/fragment_car_detail.xml
Labels: 🔨 Refactor, ✒ Reviewing, 현지
