Repository boostcampwm-2022/android01-UCMC, pull requests merged in 2022-11, with the labels that each got.

#3 Feat#0: 라이브러리 추가
  app/build.gradle
  app/src/main/java/com/gta/ucmc/UCMCApplication.kt
  build.gradle
  data/build.gradle
  domain/build.gradle
  presentation/build.gradle
Labels: ✨ Feature, ✒ Reviewing, 현지

#18 Feature/#13 Timber 초기화
  .gitignore
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gta/ucmc/LoggerInitializer.kt
Labels: ✨ Feature, ✒ Reviewing, 주영

#23 Feature: #10 네비게이션 설정
  app/build.gradle
  app/src/main/AndroidManifest.xml
  presentation/build.gradle
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/gta/presentation/ui/LoginActivity.kt
  presentation/src/main/java/com/gta/presentation/ui/MainActivity.kt
  presentation/src/main/java/com/gta/presentation/ui/chatting/ChattingFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/map/MapFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/mypage/MyPageFragment.kt
  presentation/src/main/res/drawable/ic_bottom_nav_car.xml
  presentation/src/main/res/drawable/ic_bottom_nav_chatting.xml
  presentation/src/main/res/drawable/ic_bottom_nav_my.xml
  presentation/src/main/res/layout/activity_login.xml
  presentation/src/main/res/layout/activity_main.xml
  presentation/src/main/res/layout/fragment_chatting.xml
  presentation/src/main/res/layout/fragment_map.xml
  presentation/src/main/res/layout/fragment_mypage.xml
  presentation/src/main/res/menu/menu_bottom_nav.xml
  presentation/src/main/res/navigation/nav_main.xml
  presentation/src/main/res/values/strings.xml
Labels: ✨ Feature, ✒ Reviewing, 주영

#25 Feature: #24 BaseActivity, BaseFragment 추가
  .github/workflows/ucmcCI.yml
  app/build.gradle
  data/build.gradle
  presentation/build.gradle
  presentation/src/main/java/com/gta/presentation/ui/LoginActivity.kt
  presentation/src/main/java/com/gta/presentation/ui/MainActivity.kt
  presentation/src/main/java/com/gta/presentation/ui/base/BaseActivity.kt
  presentation/src/main/java/com/gta/presentation/ui/base/BaseFragment.kt
  presentation/src/main/res/layout/activity_main.xml
Labels: ✨ Feature, ✒ Reviewing, 민성

#26 Feature: #8 로그인 화면 구현
  .github/workflows/ucmcCI.yml
  .gitignore
  data/src/androidTest/java/com/gta/data/ExampleInstrumentedTest.kt
  presentation/build.gradle
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/gta/presentation/di/FirebaseAuthModule.kt
  presentation/src/main/java/com/gta/presentation/di/FirebaseSigninModule.kt
  presentation/src/main/java/com/gta/presentation/ui/LoginActivity.kt
  presentation/src/main/java/com/gta/presentation/ui/login/LoginActivity.kt
  presentation/src/main/java/com/gta/presentation/ui/login/LoginViewModel.kt
  presentation/src/main/res/drawable/ic_logo.xml
  presentation/src/main/res/layout/activity_login.xml
Labels: ✨ Feature, ✒ Reviewing, 민성

#30 Feature: #7 내 주변 화면 레이아웃 구성
  app/src/main/AndroidManifest.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap/ic_launcher.png
  app/src/main/res/mipmap/ic_launcher_round.png
  presentation/build.gradle
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/gta/presentation/ui/MainActivity.kt
  presentation/src/main/java/com/gta/presentation/ui/map/MapFragment.kt
  presentation/src/main/res/drawable/edittext_style.xml
  presentation/src/main/res/drawable/ic_search.xml
  presentation/src/main/res/layout/fragment_map.xml
  presentation/src/main/res/values-night/styles.xml
  presentation/src/main/res/values-night/themes.xml
  presentation/src/main/res/values/colors.xml
  presentation/src/main/res/values/styles.xml
  presentation/src/main/res/values/themes.xml
Labels: ✨ Feature, ✒ Reviewing, 동훈

#29 Feature: #27 회원가입 기능 구현
  data/src/main/java/com/gta/data/di/FirebaseModule.kt
  data/src/main/java/com/gta/data/di/LoginModule.kt
  data/src/main/java/com/gta/data/model/DrivingLicense.kt
  data/src/main/java/com/gta/data/model/UserInfo.kt
  data/src/main/java/com/gta/data/repository/LoginRepositoryImpl.kt
  data/src/main/java/com/gta/data/source/LoginDataSource.kt
  domain/src/main/java/com/gta/domain/repository/LoginRepository.kt
  domain/src/main/java/com/gta/domain/usecase/login/CheckCurrentUserUseCase.kt
  presentation/src/main/java/com/gta/presentation/di/FirebaseAuthModule.kt
  presentation/src/main/java/com/gta/presentation/di/FirebaseSigninModule.kt
  presentation/src/main/java/com/gta/presentation/ui/login/LoginActivity.kt
  presentation/src/main/java/com/gta/presentation/ui/login/LoginViewModel.kt
Labels: ✨ Feature, ✒ Reviewing, 민성

#31 Feature : #4 차 상세 페이지
  data/src/main/java/com/gta/data/di/RepositoryModule.kt
  data/src/main/java/com/gta/data/repository/CarRepositoryImpl.kt
  data/src/main/java/com/gta/data/repository/UserRepositoryImpl.kt
  domain/src/main/java/com/gta/domain/model/CarDetail.kt
  domain/src/main/java/com/gta/domain/model/UserProfile.kt
  domain/src/main/java/com/gta/domain/repository/CarRepository.kt
  domain/src/main/java/com/gta/domain/repository/UserRepository.kt
  domain/src/main/java/com/gta/domain/usecase/cardetail/GetCarDetailDataUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/cardetail/GetCarOwnerIdUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/cardetail/GetMyUserIdUserCase.kt
  domain/src/main/java/com/gta/domain/usecase/cardetail/GetNowRentUserIdUseCase.kt
  presentation/src/main/java/com/gta/presentation/model/carDetail/CarInfo.kt
  presentation/src/main/java/com/gta/presentation/model/carDetail/CarOwner.kt
  presentation/src/main/java/com/gta/presentation/ui/BindingAdapter.kt
  presentation/src/main/java/com/gta/presentation/ui/MainActivity.kt
  presentation/src/main/java/com/gta/presentation/ui/cardetail/CarDetailFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/cardetail/CarDetailViewModel.kt
  presentation/src/main/res/layout/fragment_car_detail.xml
  presentation/src/main/res/layout/include_owner_profile.xml
  presentation/src/main/res/values/strings.xml
  presentation/src/main/res/values/styles.xml
Labels: ✨ Feature, ✒ Reviewing, 현지

#36 Feature: #11 운전 면허 등록 화면 구현
  data/src/main/java/com/gta/data/di/LicenseModule.kt
  data/src/main/java/com/gta/data/model/EmptyModule.kt
  data/src/main/java/com/gta/data/model/UserInfo.kt
  data/src/main/java/com/gta/data/repository/EmptyRepositoryImpl.kt
  data/src/main/java/com/gta/data/repository/LicenseRepositoryImpl.kt
  data/src/main/java/com/gta/data/source/EmptyDataSource.kt
  data/src/main/java/com/gta/data/source/LicenseDataSource.kt
  domain/src/main/java/com/gta/domain/model/DrivingLicense.kt
  domain/src/main/java/com/gta/domain/model/EmptyModel.kt
  domain/src/main/java/com/gta/domain/repository/EmptyRepository.kt
  domain/src/main/java/com/gta/domain/repository/LicenseRepository.kt
  domain/src/main/java/com/gta/domain/usecase/EmptyUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/license/GetLicenseUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/license/SetLicenseUseCase.kt
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/gta/presentation/di/UtilModule.kt
  presentation/src/main/java/com/gta/presentation/ui/GlideModule.kt
  presentation/src/main/java/com/gta/presentation/ui/MainActivity.kt
  presentation/src/main/java/com/gta/presentation/ui/base/CameraGuideFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/license/guide/LicenseGuideFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/license/registration/LicenseRegistrationFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/license/registration/LicenseRegistrationViewModel.kt
  presentation/src/main/java/com/gta/presentation/ui/login/LoginViewModel.kt
  presentation/src/main/java/com/gta/presentation/util/EmptyUtil.kt
  presentation/src/main/java/com/gta/presentation/util/ImageUtil.kt
  presentation/src/main/res/drawable/ic_camera.xml
  presentation/src/main/res/drawable/ic_check.xml
  presentation/src/main/res/drawable/img_driving_license.png
  presentation/src/main/res/layout/fragment_camera_guide.xml
  presentation/src/main/res/layout/fragment_license_registration.xml
  presentation/src/main/res/navigation/nav_main.xml
  presentation/src/main/res/values/strings.xml
  presentation/src/main/res/xml/file_paths.xml
Labels: ✨ Feature, ✒ Reviewing, 민성

#37 Feature: #15 예약하기 화면 UI Layer 구현
  presentation/build.gradle
  presentation/src/main/java/com/gta/presentation/model/DateType.kt
  presentation/src/main/java/com/gta/presentation/model/InsuranceLevel.kt
  presentation/src/main/java/com/gta/presentation/model/ReservationDate.kt
  presentation/src/main/java/com/gta/presentation/ui/BindingAdapter.kt
  presentation/src/main/java/com/gta/presentation/ui/MainActivity.kt
  presentation/src/main/java/com/gta/presentation/ui/Reservation/ReservationFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/Reservation/ReservationViewModel.kt
  presentation/src/main/java/com/gta/presentation/util/DateUtil.kt
  presentation/src/main/java/com/gta/presentation/util/DateValidator.kt
  presentation/src/main/res/drawable/ic_all_arrow_right.xml
  presentation/src/main/res/layout/fragment_reservation.xml
  presentation/src/main/res/navigation/nav_main.xml
  presentation/src/main/res/values/colors.xml
  presentation/src/main/res/values/strings.xml
  presentation/src/main/res/values/styles.xml
  presentation/src/main/res/values/themes.xml
Labels: ✨ Feature, ✒ Reviewing, 주영

#39 Feature: #14, #16, #38 지도 마커, 상세화면 적용
  presentation/src/main/java/com/gta/presentation/ui/base/BaseFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/map/MapFragment.kt
  presentation/src/main/res/layout/fragment_car_detail.xml
  presentation/src/main/res/layout/fragment_map.xml
  presentation/src/main/res/navigation/nav_main.xml
  presentation/src/main/res/values/themes.xml
Labels: ✨ Feature, ✒ Reviewing, 동훈

#46 Feature: #45 Cloud Storage 마이그레이션
  .github/workflows/ucmcCI.yml
  data/build.gradle
  data/src/main/java/com/gta/data/di/FirebaseModule.kt
  data/src/main/java/com/gta/data/di/LicenseModule.kt
  data/src/main/java/com/gta/data/di/LoginModule.kt
  data/src/main/java/com/gta/data/di/PinkSlipModule.kt
  data/src/main/java/com/gta/data/di/UserModule.kt
  data/src/main/java/com/gta/data/model/UserInfo.kt
  data/src/main/java/com/gta/data/repository/LoginRepositoryImpl.kt
  data/src/main/java/com/gta/data/repository/PinkSlipRepositoryImpl.kt
  data/src/main/java/com/gta/data/source/LicenseDataSource.kt
  data/src/main/java/com/gta/data/source/LoginDataSource.kt
  data/src/main/java/com/gta/data/source/PinkSlipDataSource.kt
  data/src/main/java/com/gta/data/source/UserDataSource.kt
Labels: ✨ Feature, ✒ Reviewing, 민성

#48 Build : Gradle Migration
  app/build.gradle
  app/build.gradle.kts
  app/proguard-rules.pro
  build.gradle
  build.gradle.kts
  buildSrc/.gitignore
  buildSrc/build.gradle.kts
  buildSrc/src/main/java/com/gta/buildsrc/Configuration.kt
  buildSrc/src/main/java/com/gta/buildsrc/Dependencies.kt
  data/build.gradle.kts
  data/proguard-rules.pro
  domain/build.gradle
  domain/build.gradle.kts
  presentation/build.gradle
  presentation/build.gradle.kts
  presentation/proguard-rules.pro
  settings.gradle.kts
Labels: ⚙ Setting, ✒ Reviewing, 동훈

#49 Feature: #47 마이페이지 UI
  data/src/main/java/com/gta/data/di/FirebaseModule.kt
  data/src/main/java/com/gta/data/di/MyPageModule.kt
  data/src/main/java/com/gta/data/di/RepositoryModule.kt
  data/src/main/java/com/gta/data/di/UserModule.kt
  data/src/main/java/com/gta/data/model/UserInfo.kt
  data/src/main/java/com/gta/data/repository/MyPageRepositoryImpl.kt
  data/src/main/java/com/gta/data/repository/UserRepositoryImpl.kt
  data/src/main/java/com/gta/data/source/MyPageDataSource.kt
  data/src/main/java/com/gta/data/source/StorageDataSource.kt
  domain/src/main/java/com/gta/domain/model/DrivingLicense.kt
  domain/src/main/java/com/gta/domain/repository/MyPageRepository.kt
  domain/src/main/java/com/gta/domain/repository/UserRepository.kt
  domain/src/main/java/com/gta/domain/usecase/mypage/DeleteThumbnailUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/mypage/SetThumbnailUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/user/GetUserProfileUseCase.kt
  presentation/src/main/java/com/gta/presentation/ui/BindingAdapter.kt
  presentation/src/main/java/com/gta/presentation/ui/mypage/MyPageFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/mypage/MyPageViewModel.kt
  presentation/src/main/res/drawable/ic_mypage_car.xml
  presentation/src/main/res/drawable/ic_mypage_deal.xml
  presentation/src/main/res/drawable/ic_mypage_edit.xml
  presentation/src/main/res/drawable/ic_mypage_fine.xml
  presentation/src/main/res/drawable/ic_mypage_license.xml
  presentation/src/main/res/drawable/ic_mypage_payment.xml
  presentation/src/main/res/drawable/ic_mypage_thumb.xml
  presentation/src/main/res/layout/fragment_mypage.xml
  presentation/src/main/res/values/strings.xml
  presentation/src/main/res/values/styles.xml
Labels: ✨ Feature, ✒ Reviewing, 민성

#51 Feature: #17 예약하기 화면 Data Layer 구현
  data/src/main/java/com/gta/data/di/RepositoryModule.kt
  data/src/main/java/com/gta/data/di/ReservationModule.kt
  data/src/main/java/com/gta/data/model/Car.kt
  data/src/main/java/com/gta/data/repository/CarRepositoryImpl.kt
  data/src/main/java/com/gta/data/repository/ReservationRepositoryImpl.kt
  data/src/main/java/com/gta/data/source/CarDataSource.kt
  data/src/main/java/com/gta/data/source/PinkSlipDataSource.kt
  data/src/main/java/com/gta/data/source/ReservationDataSource.kt
  domain/src/main/java/com/gta/domain/model/CarRentInfo.kt
  domain/src/main/java/com/gta/domain/model/Reservation.kt
  domain/src/main/java/com/gta/domain/repository/CarRepository.kt
  domain/src/main/java/com/gta/domain/repository/ReservationRepository.kt
  domain/src/main/java/com/gta/domain/usecase/reservation/CreateReservationUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/reservation/GetCarRentInfoUseCase.kt
  presentation/src/main/java/com/gta/presentation/model/ReservationDate.kt
  presentation/src/main/java/com/gta/presentation/ui/BindingAdapter.kt
  presentation/src/main/java/com/gta/presentation/ui/reservation/ReservationFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/reservation/ReservationViewModel.kt
  presentation/src/main/res/layout/fragment_reservation.xml
  presentation/src/main/res/navigation/nav_main.xml
  presentation/src/main/res/values/strings.xml
Labels: ✨ Feature, ✒ Reviewing, 주영

#55 Feature: #42 내 차 목록 데이터 불러오기
  buildSrc/src/main/java/com/gta/buildsrc/Dependencies.kt
  data/src/main/java/com/gta/data/repository/CarRepositoryImpl.kt
  data/src/main/java/com/gta/data/source/CarDataSource.kt
  data/src/main/java/com/gta/data/source/UserDataSource.kt
  domain/src/main/java/com/gta/domain/repository/CarRepository.kt
  domain/src/main/java/com/gta/domain/usecase/cardetail/RemoveCarUseCase.kt
  presentation/src/main/java/com/gta/presentation/ui/map/MapFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/mypage/MyPageFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/mypage/mycars/MyCarsFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/mypage/mycars/MyCarsListAdapter.kt
  presentation/src/main/java/com/gta/presentation/ui/mypage/mycars/MyCarsViewModel.kt
  presentation/src/main/java/com/gta/presentation/ui/mypage/mycars/OnItemClickListener.kt
  presentation/src/main/java/com/gta/presentation/ui/pinkslip/registration/PinkSlipRegistrationFragment.kt
  presentation/src/main/res/drawable/ic_add.xml
  presentation/src/main/res/drawable/ic_delete.xml
  presentation/src/main/res/drawable/selector_background.xml
  presentation/src/main/res/layout/activity_main.xml
  presentation/src/main/res/layout/fragment_my_cars.xml
  presentation/src/main/res/layout/item_mypage_carlist.xml
  presentation/src/main/res/menu/menu_mycars_item_click.xml
  presentation/src/main/res/navigation/nav_main.xml
  presentation/src/main/res/values/strings.xml
  presentation/src/main/res/values/themes.xml
Labels: ✨ Feature, ✒ Reviewing, 동훈

#56 Feature: #52 닉네임 변경, 로그아웃 기능 추가
  data/src/main/java/com/gta/data/di/NicknameModule.kt
  data/src/main/java/com/gta/data/model/UserInfo.kt
  data/src/main/java/com/gta/data/repository/NicknameRepositoryImpl.kt
  data/src/main/java/com/gta/data/source/NicknameDataSource.kt
  domain/src/main/java/com/gta/domain/model/NicknameState.kt
  domain/src/main/java/com/gta/domain/repository/NicknameRepository.kt
  domain/src/main/java/com/gta/domain/usecase/nickname/CheckNicknameStateUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/nickname/UpdateNicknameUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/user/GetUserProfileUseCase.kt
  presentation/src/main/java/com/gta/presentation/ui/MainActivity.kt
  presentation/src/main/java/com/gta/presentation/ui/login/LoginViewModel.kt
  presentation/src/main/java/com/gta/presentation/ui/mypage/MyPageFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/mypage/MyPageViewModel.kt
  presentation/src/main/java/com/gta/presentation/ui/nickname/NicknameFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/nickname/NicknameViewModel.kt
  presentation/src/main/java/com/gta/presentation/util/FirebaseUtil.kt
  presentation/src/main/res/layout/fragment_nickname.xml
  presentation/src/main/res/navigation/nav_main.xml
  presentation/src/main/res/values/strings.xml
Labels: ✨ Feature, ✒ Reviewing, 민성

#57 Feature: #40 데이터베이스 지도 적용
  data/src/main/java/com/gta/data/repository/CarRepositoryImpl.kt
  data/src/main/java/com/gta/data/source/CarDataSource.kt
  domain/src/main/java/com/gta/domain/repository/CarRepository.kt
  domain/src/main/java/com/gta/domain/usecase/map/GetAllCarsUseCase.kt
  presentation/src/main/java/com/gta/presentation/ui/map/MapFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/map/MapViewModel.kt
  presentation/src/main/res/layout/fragment_map.xml
Labels: ✨ Feature, ✒ Reviewing, 동훈

#66 Feature : #32 차 상세 페이지 Data 모듈
  data/src/main/java/com/gta/data/model/Car.kt
  data/src/main/java/com/gta/data/model/UserInfo.kt
  data/src/main/java/com/gta/data/repository/CarRepositoryImpl.kt
  data/src/main/java/com/gta/data/repository/ReservationRepositoryImpl.kt
  data/src/main/java/com/gta/data/repository/UserRepositoryImpl.kt
  data/src/main/java/com/gta/data/source/ReservationDataSource.kt
  domain/src/main/java/com/gta/domain/model/CarDetail.kt
  domain/src/main/java/com/gta/domain/model/Reservation.kt
  domain/src/main/java/com/gta/domain/model/SimpleCar.kt
  domain/src/main/java/com/gta/domain/repository/CarRepository.kt
  domain/src/main/java/com/gta/domain/repository/ReservationRepository.kt
  domain/src/main/java/com/gta/domain/repository/UserRepository.kt
  domain/src/main/java/com/gta/domain/usecase/cardetail/GetMyUserIdUserCase.kt
  domain/src/main/java/com/gta/domain/usecase/cardetail/GetNowRentCarUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/cardetail/GetNowRentUserIdUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/cardetail/GetUseStateAboutCarUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/cardetail/SetStateAtCarDetailUseCase.kt
  presentation/src/main/java/com/gta/presentation/model/carDetail/CarInfo.kt
  presentation/src/main/java/com/gta/presentation/model/carDetail/CarOwner.kt
  presentation/src/main/java/com/gta/presentation/ui/BindingAdapter.kt
  presentation/src/main/java/com/gta/presentation/ui/MainActivity.kt
  presentation/src/main/java/com/gta/presentation/ui/cardetail/CarDetailFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/cardetail/CarDetailViewModel.kt
  presentation/src/main/res/layout/fragment_car_detail.xml
  presentation/src/main/res/layout/include_owner_profile.xml
  presentation/src/main/res/layout/item_owner_car.xml
  presentation/src/main/res/navigation/nav_main.xml
  presentation/src/main/res/values/strings.xml
Labels: ✨ Feature, ✒ Reviewing, 현지

#73 Feature: #68 차주, 대여자 평가 화면
  .github/workflows/ucmcCI.yml
  .gitignore
  data/src/main/java/com/gta/data/di/ReviewModule.kt
  data/src/main/java/com/gta/data/repository/ReviewRepositoryImpl.kt
  data/src/main/java/com/gta/data/source/ReviewDataSource.kt
  domain/src/main/java/com/gta/domain/model/ReviewDTO.kt
  domain/src/main/java/com/gta/domain/model/ReviewType.kt
  domain/src/main/java/com/gta/domain/model/UserReview.kt
  domain/src/main/java/com/gta/domain/repository/ReviewRepository.kt
  domain/src/main/java/com/gta/domain/usecase/review/AddReviewUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/review/GetReviewDTOUseCase.kt
  presentation/src/main/java/com/gta/presentation/ui/review/ReviewFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/review/ReviewViewModel.kt
  presentation/src/main/res/layout/fragment_mypage.xml
  presentation/src/main/res/layout/fragment_review.xml
  presentation/src/main/res/navigation/nav_main.xml
  presentation/src/main/res/values/strings.xml
Labels: ✨ Feature, ✒ Reviewing, 민성

#77 feature: #75 datasource를 callbackflow로 마이그레이션
  data/src/main/java/com/gta/data/repository/CarRepositoryImpl.kt
  data/src/main/java/com/gta/data/repository/LicenseRepositoryImpl.kt
  data/src/main/java/com/gta/data/repository/LoginRepositoryImpl.kt
  data/src/main/java/com/gta/data/repository/MyPageRepositoryImpl.kt
  data/src/main/java/com/gta/data/repository/NicknameRepositoryImpl.kt
  data/src/main/java/com/gta/data/repository/PinkSlipRepositoryImpl.kt
  data/src/main/java/com/gta/data/repository/ReservationRepositoryImpl.kt
  data/src/main/java/com/gta/data/repository/ReviewRepositoryImpl.kt
  data/src/main/java/com/gta/data/repository/UserRepositoryImpl.kt
  data/src/main/java/com/gta/data/source/CarDataSource.kt
  data/src/main/java/com/gta/data/source/LicenseDataSource.kt
  data/src/main/java/com/gta/data/source/LoginDataSource.kt
  data/src/main/java/com/gta/data/source/MyPageDataSource.kt
  data/src/main/java/com/gta/data/source/NicknameDataSource.kt
  data/src/main/java/com/gta/data/source/PinkSlipDataSource.kt
  data/src/main/java/com/gta/data/source/ReservationDataSource.kt
  data/src/main/java/com/gta/data/source/ReviewDataSource.kt
  data/src/main/java/com/gta/data/source/StorageDataSource.kt
  data/src/main/java/com/gta/data/source/UserDataSource.kt
  presentation/src/main/java/com/gta/presentation/ui/BindingAdapter.kt
  presentation/src/main/res/navigation/nav_main.xml
Labels: ✨ Feature, ✒ Reviewing, 민성

#80 Feat: #70 지도 검색 기능
  buildSrc/src/main/java/com/gta/buildsrc/Dependencies.kt
  data/.gitignore
  data/src/main/java/com/gta/data/di/NetworkModule.kt
  data/src/main/java/com/gta/data/di/RepositoryModule.kt
  data/src/main/java/com/gta/data/model/SearchResult.kt
  data/src/main/java/com/gta/data/repository/MapRepositoryImpl.kt
  data/src/main/java/com/gta/data/service/AddressSearchService.kt
  data/src/main/java/com/gta/data/source/MapDataSource.kt
  domain/src/main/java/com/gta/domain/model/LocationInfo.kt
  domain/src/main/java/com/gta/domain/repository/MapRepository.kt
  domain/src/main/java/com/gta/domain/usecase/map/GetSearchAddressUseCase.kt
  presentation/src/main/java/com/gta/presentation/ui/map/AutoCompleteAdapter.kt
  presentation/src/main/java/com/gta/presentation/ui/map/MapFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/map/MapViewModel.kt
  presentation/src/main/java/com/gta/presentation/ui/mypage/mycars/MyCarsFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/mypage/mycars/MyCarsListAdapter.kt
  presentation/src/main/java/com/gta/presentation/ui/mypage/mycars/MyCarsViewModel.kt
  presentation/src/main/java/com/gta/presentation/ui/mypage/mycars/OnItemClickListener.kt
  presentation/src/main/res/layout/fragment_map.xml
  presentation/src/main/res/layout/item_map_search.xml
Labels: ✨ Feature, ✒ Reviewing, 동훈

#82 Feature: #64 화면에 표시될 데이터만 받아오기
  data/src/main/java/com/gta/data/repository/CarRepositoryImpl.kt
  data/src/main/java/com/gta/data/source/CarDataSource.kt
  domain/src/main/java/com/gta/domain/repository/CarRepository.kt
  domain/src/main/java/com/gta/domain/usecase/cardetail/GetNowRentCarUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/map/GetNearCarsUseCase.kt
  presentation/src/main/java/com/gta/presentation/ui/BindingAdapter.kt
  presentation/src/main/java/com/gta/presentation/ui/map/MapFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/map/MapViewModel.kt
  presentation/src/main/java/com/gta/presentation/ui/pinkslip/registration/PinkSlipRegistrationFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/reservation/ReservationFragment.kt
Labels: ✨ Feature, ✒ Reviewing, 동훈

#86 Feature: #85 마이페이지 운전자 정보 버튼 추가, 자동차 등록증 가짓수 확대
  data/src/main/java/com/gta/data/repository/PinkSlipRepositoryImpl.kt
  data/src/main/java/com/gta/data/source/PinkSlipDataSource.kt
  presentation/src/main/res/layout/fragment_mypage.xml
  presentation/src/main/res/values/strings.xml
Labels: ✨ Feature, ✒ Reviewing, 민성

#83 Feature : #34 차 상세 수정 페이지 UI
  presentation/src/main/java/com/gta/presentation/ui/BindingAdapter.kt
  presentation/src/main/java/com/gta/presentation/ui/cardetail/CarDetailFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/cardetail/edit/CarEditFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/cardetail/edit/CarEditImagesAdapter.kt
  presentation/src/main/java/com/gta/presentation/ui/cardetail/edit/CarEditViewModel.kt
  presentation/src/main/res/layout/fragment_car_edit.xml
  presentation/src/main/res/layout/item_car_edit_image.xml
  presentation/src/main/res/navigation/nav_main.xml
  presentation/src/main/res/values/strings.xml
Labels: ✨ Feature, ✒ Reviewing, 현지

#88 Map Fragment Flow 중단
  presentation/src/main/java/com/gta/presentation/ui/map/MapFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/map/MapViewModel.kt
Labels: 🐞 Fix, ✒ Reviewing, 동훈

#89 Feature: #84 지도 키워드 검색 추가, 검색어 삭제 기능 추가
  data/src/main/java/com/gta/data/model/SearchResult.kt
  data/src/main/java/com/gta/data/repository/MapRepositoryImpl.kt
  data/src/main/java/com/gta/data/service/AddressSearchService.kt
  data/src/main/java/com/gta/data/source/MapDataSource.kt
  domain/src/main/java/com/gta/domain/model/Coordinate.kt
  domain/src/main/java/com/gta/domain/model/LocationInfo.kt
  presentation/src/main/java/com/gta/presentation/ui/map/MapFragment.kt
  presentation/src/main/res/drawable/ic_close.xml
  presentation/src/main/res/layout/fragment_map.xml
  presentation/src/main/res/layout/item_map_search.xml
Labels: ✨ Feature, ✒ Reviewing, 동훈

#90 Feature: #87 채팅 목록 화면, 채팅 화면 추가
  data/src/main/java/com/gta/data/model/Car.kt
  data/src/main/java/com/gta/data/repository/CarRepositoryImpl.kt
  domain/src/main/java/com/gta/domain/repository/CarRepository.kt
  domain/src/main/java/com/gta/domain/usecase/car/GetSimpleCarUseCase.kt
  presentation/src/main/java/com/gta/presentation/di/StreamModule.kt
  presentation/src/main/java/com/gta/presentation/ui/BindingAdapter.kt
  presentation/src/main/java/com/gta/presentation/ui/MainActivity.kt
  presentation/src/main/java/com/gta/presentation/ui/chatting/ChattingFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/chatting/chat/ChattingFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/chatting/chat/ChattingViewModel.kt
  presentation/src/main/java/com/gta/presentation/ui/chatting/list/ChattingListFragment.kt
  presentation/src/main/res/layout/fragment_chatting.xml
  presentation/src/main/res/layout/fragment_chatting_list.xml
  presentation/src/main/res/layout/include_car_summary.xml
  presentation/src/main/res/menu/menu_bottom_nav.xml
  presentation/src/main/res/navigation/nav_main.xml
  presentation/src/main/res/values/strings.xml
Labels: ✨ Feature, ✒ Reviewing, 민성

#93 Feature: #33 차 상세 페이지 이미지
  buildSrc/src/main/java/com/gta/buildsrc/Dependencies.kt
  presentation/src/main/java/com/gta/presentation/ui/cardetail/CarDetailFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/cardetail/CarDetailViewModel.kt
  presentation/src/main/java/com/gta/presentation/ui/cardetail/CarImagePagerAdapter.kt
  presentation/src/main/res/layout/fragment_car_detail.xml
  presentation/src/main/res/layout/item_car_detail_image.xml
Labels: ✨ Feature, ✒ Reviewing, 현지

#94 Feature: #72 FCM 설정, 예약 요청 알림 전송
  buildSrc/src/main/java/com/gta/buildsrc/Dependencies.kt
  data/src/main/java/com/gta/data/di/LoginModule.kt
  data/src/main/java/com/gta/data/di/MessageTokenModule.kt
  data/src/main/java/com/gta/data/di/NetworkModule.kt
  data/src/main/java/com/gta/data/di/NotificationModule.kt
  data/src/main/java/com/gta/data/di/Qualifiers.kt
  data/src/main/java/com/gta/data/model/Car.kt
  data/src/main/java/com/gta/data/model/MessageResult.kt
  data/src/main/java/com/gta/data/model/NotificationMessage.kt
  data/src/main/java/com/gta/data/model/UserInfo.kt
  data/src/main/java/com/gta/data/repository/CarRepositoryImpl.kt
  data/src/main/java/com/gta/data/repository/LoginRepositoryImpl.kt
  data/src/main/java/com/gta/data/repository/MessageTokenRepositoryImpl.kt
  data/src/main/java/com/gta/data/repository/NotificationRepositoryImpl.kt
  data/src/main/java/com/gta/data/repository/ReservationRepositoryImpl.kt
  data/src/main/java/com/gta/data/repository/ReviewRepositoryImpl.kt
  data/src/main/java/com/gta/data/service/CloudMessageService.kt
  data/src/main/java/com/gta/data/source/CarDataSource.kt
  data/src/main/java/com/gta/data/source/LoginDataSource.kt
  data/src/main/java/com/gta/data/source/MessageTokenDataSource.kt
  data/src/main/java/com/gta/data/source/NotificationDataSource.kt
  data/src/main/java/com/gta/data/source/ReservationDataSource.kt
  domain/src/main/java/com/gta/domain/model/CarRentInfo.kt
  domain/src/main/java/com/gta/domain/model/Notification.kt
  domain/src/main/java/com/gta/domain/repository/MessageTokenRepository.kt
  domain/src/main/java/com/gta/domain/repository/NotificationRepository.kt
  domain/src/main/java/com/gta/domain/repository/ReservationRepository.kt
  domain/src/main/java/com/gta/domain/repository/ReviewRepository.kt
  domain/src/main/java/com/gta/domain/usecase/SendNotificationUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/cardetail/GetNowRentCarUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/cardetail/GetUseStateAboutCarUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/notification/SetMessageTokenUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/reservation/CreateReservationUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/review/GetReviewDTOUseCase.kt
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/gta/presentation/NotificationService.kt
  presentation/src/main/java/com/gta/presentation/ui/reservation/PaymentFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/reservation/ReservationViewModel.kt
  presentation/src/main/java/com/gta/presentation/ui/review/ReviewViewModel.kt
  presentation/src/main/res/navigation/nav_main.xml
  presentation/src/main/res/values/strings.xml
Labels: ✨ Feature, ✒ Reviewing, 주영

#101 Feature #100 : 앱 데이터 삭제 시 FCM 토큰 정보 업데이트
  data/src/main/java/com/gta/data/repository/LoginRepositoryImpl.kt
  data/src/main/java/com/gta/data/source/UserDataSource.kt
  domain/src/main/java/com/gta/domain/repository/LoginRepository.kt
  domain/src/main/java/com/gta/domain/usecase/login/CheckCurrentUserUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/login/UpdateUserMessageTokenUseCase.kt
  presentation/src/main/java/com/gta/presentation/ui/login/LoginViewModel.kt
Labels: ✨ Feature, ✒ Reviewing, 주영

#103 Feature: #97 채팅방 생성, 유저 프로필 변경 감시
  buildSrc/src/main/java/com/gta/buildsrc/Dependencies.kt
  presentation/src/main/java/com/gta/presentation/di/StreamModule.kt
  presentation/src/main/java/com/gta/presentation/ui/MainActivity.kt
  presentation/src/main/java/com/gta/presentation/ui/MainViewModel.kt
  presentation/src/main/java/com/gta/presentation/ui/cardetail/CarDetailFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/cardetail/CarDetailViewModel.kt
  presentation/src/main/java/com/gta/presentation/ui/chatting/chat/ChattingFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/chatting/chat/ChattingViewModel.kt
  presentation/src/main/java/com/gta/presentation/ui/chatting/list/ChattingListFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/login/LoginActivity.kt
  presentation/src/main/java/com/gta/presentation/ui/login/LoginViewModel.kt
  presentation/src/main/java/com/gta/presentation/ui/map/MapFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/map/MapViewModel.kt
  presentation/src/main/java/com/gta/presentation/ui/mypage/MyPageViewModel.kt
  presentation/src/main/java/com/gta/presentation/ui/nickname/NicknameFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/nickname/NicknameViewModel.kt
  presentation/src/main/java/com/gta/presentation/util/RepeatOnStarted.kt
  presentation/src/main/res/layout/fragment_car_detail.xml
  presentation/src/main/res/layout/fragment_map.xml
  presentation/src/main/res/layout/item_mypage_carlist.xml
  presentation/src/main/res/navigation/nav_main.xml
Labels: ✨ Feature, ✒ Reviewing, 민성

#105 Feature : #76 차 상세 수정 페이지(내차 수정하기) DB 반영
  buildSrc/src/main/java/com/gta/buildsrc/Dependencies.kt
  data/src/main/java/com/gta/data/di/RepositoryModule.kt
  data/src/main/java/com/gta/data/model/Car.kt
  data/src/main/java/com/gta/data/repository/CarRepositoryImpl.kt
  data/src/main/java/com/gta/data/source/CarDataSource.kt
  data/src/main/java/com/gta/data/source/StorageDataSource.kt
  domain/src/main/java/com/gta/domain/model/UpdateCar.kt
  domain/src/main/java/com/gta/domain/repository/CarRepository.kt
  domain/src/main/java/com/gta/domain/usecase/cardetail/edit/DeleteImagesUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/cardetail/edit/SetCarImagesUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/cardetail/edit/UpdateCarDetailDataUseCase.kt
  domain/src/main/java/com/gta/domain/usecase/cardetail/edit/UploadCarImagesUseCase.kt
  presentation/src/main/java/com/gta/presentation/ui/cardetail/edit/CarEditFragment.kt
  presentation/src/main/java/com/gta/presentation/ui/cardetail/edit/CarEditViewModel.kt
  presentation/src/main/res/layout/fragment_car_edit.xml
  presentation/src/main/res/layout/include_wait_loading.xml
  presentation/src/main/res/raw/lottie_car.json
  presentation/src/main/res/values/strings.xml
Labels: ✨ Feature, ✒ Reviewing, 현지
